; Script generated by the Inno Setup Script Wizard.

#define GetVersion(FileName) \
  Local[0] = FileOpen(FileName), \
  Local[1] = FileRead(Local[0]), \
  FileClose(Local[0]), \
  Local[2] = Trim(Copy(Local[1], Pos(": ", Local[1]) + 2, 100)), \
  Local[2]


#define MyAppName "Rec2CDF"
#define MyAppPublisher "NIWA"
#define MyAppURL "https://www.niwa.co.nz"
#define MyAppExeName "rec2cdf.exe"
#define MyAppVersion GetVersion("bin\version.txt")



  



[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{3F117187-0DEB-47DD-B91C-D6C0ECF26533}
AppName={#MyAppName}
AppPublisher={#MyAppPublisher}
AppVersion={#MyAppVersion}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users.)
PrivilegesRequired=lowest
OutputBaseFilename=rec2cdfsetup-{#MyAppVersion}
SetupIconFile=C:\Users\mattw\Documents\rec2cdf\dist\rec2cdf\_internal\rec2cdf.ico
Compression=lzma
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\Users\mattw\Documents\rec2cdf\build\rec2cdf\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\Users\mattw\Documents\rec2cdf\dist\rec2cdf\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs createallsubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

